# Application Configuration
server:
  port: 8090
  
# H2 Console in Browser
# http://localhost:8090/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      
# DB Config
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
# JPA/Hibernate
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false

#logging:
#  pattern:
#    console: "%{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN: -%5p} %m%n"

