# Application Configuration
server:
  port: 8092
  
msg:
  print: Mensaje de DEV shopping

spring:
  application:
    name: shopping-service

#logging:
#  pattern:
#    console: "%{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN: -%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka

Feing:
  hystrix:
    dashboard:
      proxyStreamAllowList=*
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
